const schema = {
  project_id: '',
  country_fk: '',
  slug: '',
  name: '',
  property_header_info: {
    name: '',
    short_description: '',
    descriptions: [],
    cover_picture_url: '',
  },
  location: {
    address: '',
    lat: null,
    lng: null,
    google_map_url: '',
  },
  location_map: [],
  features: [],
  location_nearby: [],
  units_available_for_purchase: [],
  videos: [],
  team_behind: {},
  completion_status: null,
  availability: null,
  pricing_description: '',
  bedrooms_description: '',
  residences_description: '',
  estimated_completion: '',
  units_available: '',
  description: '',
  brochure_url: '',
  images: [],
  breadcrumbs: [],
};

module.exports = schema;
